[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ips_client"
author = "brighter AI"
author-email = "dev@brighter.ai"
home-page = "https://github.com/brighter-ai"
requires-python = ">=3.6"
requires = [
    "httpx~=0.16.1",
    "pydantic~=1.6.1",
    "requests~=2.24.0",
    "tqdm~=4.52.0",
    "typer~=0.3.2"
]
