[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.scripts]
redact_file = "redact.__main__:redact_file_entry_point"
redact_folder = "redact.__main__:redact_folder_entry_point"

[tool.flit.metadata]
module = "redact"
author = "brighter AI"
author-email = "dev@brighter.ai"
home-page = "https://github.com/brighter-ai"
requires-python = ">=3.6"
requires = [
    "httpcore~=0.12.3",
    "httpx~=0.17.1",
    "pydantic~=1.8.1",
    "tqdm~=4.60.0",
    "typer~=0.3.2"
]
